package com.wnslp.ssm.domain.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table inf_parm
 */
public class InfParm implements Serializable {
    /**
     * Database Column Remarks:
     *   id值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inf_parm.id
     *
     * @mbg.generated Thu Aug 20 00:03:32 CST 2020
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   参数值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inf_parm.parm_value
     *
     * @mbg.generated Thu Aug 20 00:03:32 CST 2020
     */
    private String parmValue;

    /**
     * Database Column Remarks:
     *   参数名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inf_parm.parm_name
     *
     * @mbg.generated Thu Aug 20 00:03:32 CST 2020
     */
    private String parmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inf_parm
     *
     * @mbg.generated Thu Aug 20 00:03:32 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inf_parm.id
     *
     * @return the value of inf_parm.id
     *
     * @mbg.generated Thu Aug 20 00:03:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inf_parm.id
     *
     * @param id the value for inf_parm.id
     *
     * @mbg.generated Thu Aug 20 00:03:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inf_parm.parm_value
     *
     * @return the value of inf_parm.parm_value
     *
     * @mbg.generated Thu Aug 20 00:03:32 CST 2020
     */
    public String getParmValue() {
        return parmValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inf_parm.parm_value
     *
     * @param parmValue the value for inf_parm.parm_value
     *
     * @mbg.generated Thu Aug 20 00:03:32 CST 2020
     */
    public void setParmValue(String parmValue) {
        this.parmValue = parmValue == null ? null : parmValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inf_parm.parm_name
     *
     * @return the value of inf_parm.parm_name
     *
     * @mbg.generated Thu Aug 20 00:03:32 CST 2020
     */
    public String getParmName() {
        return parmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inf_parm.parm_name
     *
     * @param parmName the value for inf_parm.parm_name
     *
     * @mbg.generated Thu Aug 20 00:03:32 CST 2020
     */
    public void setParmName(String parmName) {
        this.parmName = parmName == null ? null : parmName.trim();
    }
}